package alavanca;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JToolBar;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

import alavanca.gui.InfoFrame;
import alavanca.gui.ShowFrameAction;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App extends JPanel {
	
	static final int WIDTH = 600;
	static final int HEIGHT = 480;
	
	private EngrenagemView engrenagemEscravo;
	private EngrenagemView engrenagemMestre;
	private BarraView barra;
	
	private MouseHandler mouseHandler;
	private PlayAction playAction;
	private StopAction stopAction;
	
	private Timer playTimer;
	private final int frameMs = 1000/30;
	private double radPerSec = Math.PI;
	
	private InfoFrame infoFrame;
	private ShowFrameAction showInfoAction;
	
	public App() {
		this.setPreferredSize(new Dimension(WIDTH, HEIGHT));
		
		setBackground(Color.WHITE);
		
		Engrenagem escravo = new Engrenagem();
		Engrenagem mestre = new Engrenagem();
		
		mestre.setCentro(200, 200);
		mestre.setAlfa(Math.PI/2);
		mestre.setRaioBarra(20);
		
		escravo.setAlfa(Math.PI/4);
		
		Barra barraModel = new Barra(escravo, mestre);
		
		barra = new BarraView(barraModel);
		
		engrenagemEscravo = new EngrenagemView(escravo);
		engrenagemMestre = new EngrenagemView(mestre);		
	
		playTimer = new Timer(frameMs, (ev) -> {
			double alfa = mestre.getAlfa();
			alfa += (radPerSec * frameMs)/1000;
			mestre.setAlfa(alfa);
			repaint();
		});
				
		playAction = new PlayAction();
		stopAction = new StopAction();
		
		infoFrame = new InfoFrame(mestre, escravo, barraModel);
		showInfoAction = new ShowFrameAction(infoFrame, "Info");
		
		mouseHandler = new MouseHandler();
		addMouseListener(mouseHandler);
		addMouseMotionListener(mouseHandler);
	}
	
    @Override
	protected void paintComponent(Graphics g) {
		super.paintComponent(g);
		
		Graphics2D g2 = (Graphics2D) g;
		
		engrenagemEscravo.paint(g2);
		engrenagemMestre.paint(g2);
		barra.paint(g2);
	}

    public double getRadPerSec() {
		return radPerSec;
	}

	public void setRadPerSec(double radPerSec) {
		this.radPerSec = radPerSec;
	}

	public PlayAction getPlayAction() {
		return playAction;
	}

	public StopAction getStopAction() {
		return stopAction;
	}

	public int getFrameMs() {
		return frameMs;
	}

	public ShowFrameAction getShowInfoAction() {
		return showInfoAction;
	}

	private class MouseHandler extends MouseAdapter {
    	private EngrenagemView selected; 
    	
    	@Override
		public void mouseDragged(MouseEvent e) {
    		if (selected != null) {
    			selected.getEngrenagem().setCentro(e.getPoint());
    		}
    		
    		repaint();
    	}

		@Override
		public void mousePressed(MouseEvent e) {
			if (engrenagemMestre.contains(e.getPoint())) {
				selected = engrenagemMestre;
			} else if (engrenagemEscravo.contains(e.getPoint())) {
				selected = engrenagemEscravo;
			}
		}

		@Override
		public void mouseReleased(MouseEvent e) {
			selected = null;
		}
    }
    
    private class PlayAction extends AbstractAction {
    	public PlayAction() {
    		super("Play");
    	}
    	
    	@Override
		public void actionPerformed(ActionEvent e) {
			setEnabled(false);
			App.this.stopAction.setEnabled(true);
			App.this.playTimer.start();
    	}
    }
    
    private class StopAction extends AbstractAction {
    	public StopAction() {
    		super("Stop");
    		setEnabled(false);
    	}
    	
    	@Override
		public void actionPerformed(ActionEvent e) {
    		App.this.playTimer.stop();
			App.this.playAction.setEnabled(true);
			setEnabled(false);
		}
    }
    
    public static void main(String[] args) {
    	SwingUtilities.invokeLater( () -> {
    		JFrame frame = new JFrame("Alavanca e Engrenagens");
    		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    		
    		JPanel panel = new JPanel(new BorderLayout());
    		
    		App app = new App();
    		
    		JToolBar toolBar = new JToolBar("Tool Bar");
    		JButton btnPlay = new JButton(app.getPlayAction());
    		toolBar.add(btnPlay);
    		JButton btnStop = new JButton(app.getStopAction());
    		toolBar.add(btnStop);
    		
    		JButton btnInfo = new JButton(app.getShowInfoAction());
    		toolBar.add(btnInfo);

    		panel.add(app, BorderLayout.CENTER);
    		panel.add(toolBar, BorderLayout.NORTH);
    		
    		frame.add(panel);
    		
    		frame.pack();
    		frame.setVisible(true);
    	});
    }
}
